### ISSUE TITLE
Instagram account hacked 

### ISSUE THREAD

**Issue by Dashubhai** [evildevill/Tmux_pckg#2]
Instagram account @oye_miss_verma_
Instagram password hack

**Comment by B12Tu** [comment]
I'd hack krni h bhai

**Comment by SridharPalanisamy1** [comment]
Is that your ID?

**Comment by Michealflair** [comment]
DM 𝐆𝐀𝐑𝐈𝐕𝐓𝐄𝐂𝐇 on instagram he recovered my hacked instagram account in less than 45min he will help you

**Comment by Shailukirar** [comment]
Shivi_thakur8462
Is I'd ka pasward chaiye sir

**Comment by B12Tu** [comment]
Sir password chaiye golu_jaan_14140

**Comment by leserial** [comment]
please hack alicette_prs instagram ?

**Comment by Lynsad** [comment]
> Sir password chaiye golu_jaan_14140

Can u hack rafa_arteaga98 please? 
Thank u so much

**Comment by B12Tu** [comment]
> Is that your ID?

Golu_jaan_14140
